name = "telemetry_lmu"
product-name = "Telemetry LMU"
version = "0.2.3"
before-packaging-command = "cargo build --release --target x86_64-pc-windows-gnu"
formats = ["nsis"]
out-dir = "../dist/windows"
icons = ["../packaging/app_icons/icon.ico"]
target-triple = "x86_64-pc-windows-gnu"

[nsis]
installer-icon = "../packaging/app_icons/icon.ico"

[[binaries]]
path = "../../target/x86_64-pc-windows-gnu/release/telemetry_lmu.exe"
main = true
